site_name: PyReel Documentation
site_url: https://tuckertrost.github.io/pyreel
theme:
  name: material
  icon:
    logo: fontawesome/solid/film
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: pink

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: pink

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false

nav:
  - Home: index.md
  - API Reference: API.md
  - Code Examples: code-examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tuckertrost/pyreel

copyright: Copyright &copy; 2026 Tucker Trost
