# example_package/math_utils.py

def multiply(value: float, factor: float = 2.0) -> float:
    """Multiply a value by a given factor.

    This is a simple example function intended for use in documentation
    generated by mkdocstrings.

    Args:
        value: The number to be multiplied.
        factor: The factor to multiply ``value`` by. Defaults to 2.0.

    Returns:
        The product of ``value`` and ``factor``.

    Examples:
        >>> multiply(3, 4)
        12
        >>> multiply(5)
        10.0
    """
    return value * factor
